name: testing-environment 

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch: 
  # workflow_run: triggered after "otherworkflow" completed
    # workflows: [ "otherworkflow" ] 
    # types: [ completed ]

jobs:
  setup-go-k8s:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v2.3.4
        timeout-minutes: 10
      - name: setup-go 
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: go version
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Kubernetes info
        timeout-minutes: 5
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          cat ~/.kube/config
          ls -lah ~/.kube/config
          cd ~/.kube/
          pwd
      - name: pro info
        run: |
          cd ~
          ls
          pwd
