name: testing-environment 

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch: 
  # workflow_run: triggered after "otherworkflow" completed
    # workflows: [ "otherworkflow" ] 
    # types: [ completed ]

jobs:
  setup-go-k8s:
    runs-on: self-hosted
    steps: 
      - name: checkout code
        uses: actions/checkout@v2.3.4
        timeout-minutes: 10
      - name: Kubernetes info
        timeout-minutes: 5
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          cat ~/.kube/config
          ls -lah ~/.kube/config
          cd ~/.kube/
          pwd
      - name: workspace path
        run: |
          echo -e "\033[35m home path is $HOME \033[0m"
          echo -e "\033[35m workspace path is `pwd` \033[0m"
